### ISSUE TITLE
Retries reporting

### ISSUE THREAD

**Issue by cbrunnkvist** [prma85/cypress-teamcity-reporter#34]
## Describe the solution you'd like
Now since Cypress version 5.x.x when [test retries](https://docs.cypress.io/guides/guides/test-retries.html) is more of a first-class feature, it would make sense to report retries per test as [custom test metadata](https://www.jetbrains.com/help/teamcity/reporting-test-metadata.html#Numbers), and the total number of retries as a [build statistic](https://www.jetbrains.com/help/teamcity/service-messages.html#Reporting+Build+Statistics).

**Comment by alh-solidatus** [comment]
@prma85 Is this something you'd be interested in implementing? Would definitely be a nice to have :)

**Comment by prma85** [comment]
Yeah, for sure. I missed it. I will add it next week 😉
