### ISSUE TITLE
How is this different from bundled reporter?

### ISSUE THREAD

**Issue by cbrunnkvist** [prma85/cypress-teamcity-reporter#39]
## Is your feature request related to a problem? Please describe

I think it would be nice to add to the README what the differences / advantages of using this module is, as compared to [the  `@cypress-io/mocha-teamcity-reporter` one](https://github.com/cypress-io/mocha-teamcity-reporter) that comes [bundled with Cypress](https://github.com/cypress-io/mocha-teamcity-reporter), which itself seems to be a few years' worth of bugfixes behind its upstream version.

**Comment by cbrunnkvist** [comment]
(Would of course be nice to get @bahmutov's input on this too...)

**Comment by prma85** [comment]
Will add it 👍
Bit the difference is more on how it is printed using TC TAGS while using Mocha one it prints a little messy
