### ISSUE TITLE
description inside describe block should precede the description in it block. 

### ISSUE THREAD

**Issue by puggerina** [prma85/cypress-teamcity-reporter#46]

**Comment by puggerina** [comment]
my describe block looks like this
describe('Login', () => {

my it block looks like this 
it(['smoke'],'Verify all elements on Login Page ', () => {

Note"['smoke'] is my tag

when my tests run on TC using the cypress -teamcity reporter I would like to see the tests published like

Login -Verify all elements on Login Page

not sure if this option is already available through some settings and configuration setting for this . Hope to get some help

**Comment by prma85** [comment]
@puggerina there are no settings for the report but the describe is printed as first item in the test
